/*

This file was generated by the "C - Kessels engine grammar.h" template.

*/


wchar_t GrammarCharset0[27+1] = {
  9,
  10,
  11,
  12,
  13,
  32,
  133,
  160,
  5760,
  6158,
  8192,
  8193,
  8194,
  8195,
  8196,
  8197,
  8198,
  8199,
  8200,
  8201,
  8202,
  8230,
  8232,
  8233,
  8239,
  8287,
  12288,
  0};
wchar_t GrammarCharset1[1+1] = {
  39,
  0};
wchar_t GrammarCharset2[1+1] = {
  45,
  0};
wchar_t GrammarCharset3[1+1] = {
  33,
  0};
wchar_t GrammarCharset4[1+1] = {
  37,
  0};
wchar_t GrammarCharset5[1+1] = {
  40,
  0};
wchar_t GrammarCharset6[1+1] = {
  41,
  0};
wchar_t GrammarCharset7[1+1] = {
  42,
  0};
wchar_t GrammarCharset8[1+1] = {
  44,
  0};
wchar_t GrammarCharset9[1+1] = {
  47,
  0};
wchar_t GrammarCharset10[1+1] = {
  59,
  0};
wchar_t GrammarCharset11[1+1] = {
  123,
  0};
wchar_t GrammarCharset12[1+1] = {
  125,
  0};
wchar_t GrammarCharset13[1+1] = {
  43,
  0};
wchar_t GrammarCharset14[1+1] = {
  60,
  0};
wchar_t GrammarCharset15[1+1] = {
  62,
  0};
wchar_t GrammarCharset16[1+1] = {
  65,
  0};
wchar_t GrammarCharset17[1+1] = {
  69,
  0};
wchar_t GrammarCharset18[1+1] = {
  70,
  0};
wchar_t GrammarCharset19[1+1] = {
  76,
  0};
wchar_t GrammarCharset20[1+1] = {
  78,
  0};
wchar_t GrammarCharset21[1+1] = {
  79,
  0};
wchar_t GrammarCharset22[1+1] = {
  82,
  0};
wchar_t GrammarCharset23[1+1] = {
  61,
  0};
wchar_t GrammarCharset24[1+1] = {
  73,
  0};
wchar_t GrammarCharset25[1+1] = {
  68,
  0};
wchar_t GrammarCharset26[1+1] = {
  83,
  0};
wchar_t GrammarCharset27[1+1] = {
  85,
  0};
wchar_t GrammarCharset28[1+1] = {
  67,
  0};
wchar_t GrammarCharset29[1+1] = {
  84,
  0};
wchar_t GrammarCharset30[1+1] = {
  80,
  0};
wchar_t GrammarCharset31[1+1] = {
  77,
  0};



struct DfaEdgeStruct GrammarDfaEdgeArray0[25+1] = {
  {1,GrammarCharset0},
  {2,GrammarCharset1},
  {3,GrammarCharset2},
  {4,GrammarCharset3},
  {6,GrammarCharset4},
  {7,GrammarCharset5},
  {8,GrammarCharset6},
  {9,GrammarCharset7},
  {10,GrammarCharset8},
  {11,GrammarCharset9},
  {12,GrammarCharset10},
  {13,GrammarCharset11},
  {14,GrammarCharset12},
  {15,GrammarCharset13},
  {16,GrammarCharset14},
  {17,GrammarCharset15},
  {18,GrammarCharset16},
  {21,GrammarCharset17},
  {25,GrammarCharset18},
  {33,GrammarCharset19},
  {37,GrammarCharset20},
  {40,GrammarCharset21},
  {42,GrammarCharset22},
  {48,GrammarCharset23},
  {50,GrammarCharset24},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray1[1+1] = {
  {1,GrammarCharset0},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray2[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray3[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray4[1+1] = {
  {5,GrammarCharset23},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray5[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray6[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray7[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray8[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray9[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray10[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray11[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray12[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray13[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray14[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray15[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray16[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray17[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray18[1+1] = {
  {19,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray19[1+1] = {
  {20,GrammarCharset25},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray20[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray21[1+1] = {
  {22,GrammarCharset19},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray22[1+1] = {
  {23,GrammarCharset26},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray23[1+1] = {
  {24,GrammarCharset17},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray24[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray25[1+1] = {
  {26,GrammarCharset27},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray26[1+1] = {
  {27,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray27[1+1] = {
  {28,GrammarCharset28},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray28[1+1] = {
  {29,GrammarCharset29},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray29[1+1] = {
  {30,GrammarCharset24},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray30[1+1] = {
  {31,GrammarCharset21},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray31[1+1] = {
  {32,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray32[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray33[1+1] = {
  {34,GrammarCharset21},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray34[1+1] = {
  {35,GrammarCharset21},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray35[1+1] = {
  {36,GrammarCharset30},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray36[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray37[1+1] = {
  {38,GrammarCharset27},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray38[1+1] = {
  {39,GrammarCharset31},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray39[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray40[1+1] = {
  {41,GrammarCharset22},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray41[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray42[1+1] = {
  {43,GrammarCharset17},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray43[1+1] = {
  {44,GrammarCharset29},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray44[1+1] = {
  {45,GrammarCharset27},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray45[1+1] = {
  {46,GrammarCharset22},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray46[1+1] = {
  {47,GrammarCharset20},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray47[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray48[1+1] = {
  {49,GrammarCharset23},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray49[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray50[2+1] = {
  {51,GrammarCharset25},
  {52,GrammarCharset18},
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray51[0+1] = {
  {-1,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray52[0+1] = {
  {-1,NULL}};



int GrammarRuleSymbolArray0[1+1] = {
  15,
  -1};
int GrammarRuleSymbolArray1[1+1] = {
  4,
  -1};
int GrammarRuleSymbolArray2[1+1] = {
  27,
  -1};
int GrammarRuleSymbolArray3[1+1] = {
  9,
  -1};
int GrammarRuleSymbolArray4[1+1] = {
  11,
  -1};
int GrammarRuleSymbolArray5[1+1] = {
  6,
  -1};
int GrammarRuleSymbolArray6[1+1] = {
  20,
  -1};
int GrammarRuleSymbolArray7[3+1] = {
  34,
  30,
  43,
  -1};
int GrammarRuleSymbolArray8[1+1] = {
  43,
  -1};
int GrammarRuleSymbolArray9[3+1] = {
  43,
  29,
  35,
  -1};
int GrammarRuleSymbolArray10[1+1] = {
  35,
  -1};
int GrammarRuleSymbolArray11[3+1] = {
  7,
  34,
  8,
  -1};
int GrammarRuleSymbolArray12[1+1] = {
  23,
  -1};
int GrammarRuleSymbolArray13[1+1] = {
  26,
  -1};
int GrammarRuleSymbolArray14[3+1] = {
  34,
  5,
  34,
  -1};
int GrammarRuleSymbolArray15[3+1] = {
  34,
  18,
  34,
  -1};
int GrammarRuleSymbolArray16[3+1] = {
  34,
  16,
  34,
  -1};
int GrammarRuleSymbolArray17[3+1] = {
  34,
  19,
  34,
  -1};
int GrammarRuleSymbolArray18[5+1] = {
  24,
  39,
  41,
  21,
  41,
  -1};
int GrammarRuleSymbolArray19[3+1] = {
  23,
  17,
  34,
  -1};
int GrammarRuleSymbolArray20[3+1] = {
  23,
  17,
  39,
  -1};
int GrammarRuleSymbolArray21[5+1] = {
  25,
  7,
  39,
  8,
  41,
  -1};
int GrammarRuleSymbolArray22[5+1] = {
  25,
  41,
  7,
  39,
  8,
  -1};
int GrammarRuleSymbolArray23[1+1] = {
  38,
  -1};
int GrammarRuleSymbolArray24[1+1] = {
  33,
  -1};
int GrammarRuleSymbolArray25[2+1] = {
  31,
  12,
  -1};
int GrammarRuleSymbolArray26[1+1] = {
  36,
  -1};
int GrammarRuleSymbolArray27[2+1] = {
  36,
  37,
  -1};
int GrammarRuleSymbolArray28[1+1] = {
  36,
  -1};
int GrammarRuleSymbolArray29[1+1] = {
  3,
  -1};
int GrammarRuleSymbolArray30[2+1] = {
  13,
  42,
  -1};
int GrammarRuleSymbolArray31[1+1] = {
  32,
  -1};
int GrammarRuleSymbolArray32[3+1] = {
  28,
  39,
  12,
  -1};
int GrammarRuleSymbolArray33[3+1] = {
  28,
  34,
  12,
  -1};
int GrammarRuleSymbolArray34[2+1] = {
  32,
  42,
  -1};
int GrammarRuleSymbolArray35[1+1] = {
  14,
  -1};
int GrammarRuleSymbolArray36[4+1] = {
  28,
  39,
  12,
  14,
  -1};
int GrammarRuleSymbolArray37[4+1] = {
  28,
  34,
  12,
  14,
  -1};
int GrammarRuleSymbolArray38[5+1] = {
  22,
  23,
  7,
  40,
  41,
  -1};
int GrammarRuleSymbolArray39[2+1] = {
  23,
  8,
  -1};
int GrammarRuleSymbolArray40[1+1] = {
  8,
  -1};
int GrammarRuleSymbolArray41[3+1] = {
  23,
  10,
  40,
  -1};


struct ActionStruct GrammarLalrActionArray0[4+1] = {
  {3,1,1},
  {22,1,2},
  {36,3,3},
  {37,3,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray1[1+1] = {
  {0,2,29},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray2[1+1] = {
  {23,1,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray3[5+1] = {
  {3,1,1},
  {22,1,2},
  {36,3,3},
  {37,3,6},
  {0,2,28},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray4[1+1] = {
  {0,4,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray5[1+1] = {
  {7,1,7},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray6[1+1] = {
  {0,2,27},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray7[3+1] = {
  {8,1,8},
  {23,1,9},
  {40,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray8[6+1] = {
  {13,2,40},
  {22,2,40},
  {23,2,40},
  {24,2,40},
  {25,2,40},
  {28,2,40},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray9[2+1] = {
  {8,1,11},
  {10,1,12},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray10[12+1] = {
  {13,1,13},
  {22,1,2},
  {23,1,14},
  {24,1,15},
  {25,1,16},
  {28,1,17},
  {31,3,18},
  {32,3,19},
  {33,3,20},
  {36,3,21},
  {38,3,22},
  {41,3,23},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray11[6+1] = {
  {13,2,39},
  {22,2,39},
  {23,2,39},
  {24,2,39},
  {25,2,39},
  {28,2,39},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray12[3+1] = {
  {8,1,8},
  {23,1,9},
  {40,3,24},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray13[12+1] = {
  {14,1,25},
  {22,1,2},
  {23,1,14},
  {24,1,15},
  {25,1,16},
  {28,1,26},
  {31,3,18},
  {32,3,27},
  {33,3,20},
  {36,3,21},
  {38,3,22},
  {42,3,28},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray14[1+1] = {
  {17,1,29},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray15[7+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,33},
  {35,3,34},
  {39,3,35},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray16[13+1] = {
  {7,1,37},
  {13,1,13},
  {22,1,2},
  {23,1,14},
  {24,1,15},
  {25,1,16},
  {28,1,17},
  {31,3,18},
  {32,3,19},
  {33,3,20},
  {36,3,21},
  {38,3,22},
  {41,3,38},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray17[7+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,39},
  {35,3,34},
  {39,3,40},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray18[1+1] = {
  {12,1,41},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray19[10+1] = {
  {0,2,31},
  {3,2,31},
  {7,2,31},
  {14,2,31},
  {21,2,31},
  {22,2,31},
  {23,2,31},
  {24,2,31},
  {25,2,31},
  {28,2,31},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray20[10+1] = {
  {0,2,24},
  {3,2,24},
  {7,2,24},
  {14,2,24},
  {21,2,24},
  {22,2,24},
  {23,2,24},
  {24,2,24},
  {25,2,24},
  {28,2,24},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray21[10+1] = {
  {0,2,26},
  {3,2,26},
  {7,2,26},
  {14,2,26},
  {21,2,26},
  {22,2,26},
  {23,2,26},
  {24,2,26},
  {25,2,26},
  {28,2,26},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray22[10+1] = {
  {0,2,23},
  {3,2,23},
  {7,2,23},
  {14,2,23},
  {21,2,23},
  {22,2,23},
  {23,2,23},
  {24,2,23},
  {25,2,23},
  {28,2,23},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray23[10+1] = {
  {0,2,38},
  {3,2,38},
  {7,2,38},
  {14,2,38},
  {21,2,38},
  {22,2,38},
  {23,2,38},
  {24,2,38},
  {25,2,38},
  {28,2,38},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray24[6+1] = {
  {13,2,41},
  {22,2,41},
  {23,2,41},
  {24,2,41},
  {25,2,41},
  {28,2,41},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray25[10+1] = {
  {0,2,35},
  {3,2,35},
  {7,2,35},
  {14,2,35},
  {21,2,35},
  {22,2,35},
  {23,2,35},
  {24,2,35},
  {25,2,35},
  {28,2,35},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray26[7+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,42},
  {35,3,34},
  {39,3,43},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray27[12+1] = {
  {14,1,25},
  {22,1,2},
  {23,1,14},
  {24,1,15},
  {25,1,16},
  {28,1,26},
  {31,3,18},
  {32,3,27},
  {33,3,20},
  {36,3,21},
  {38,3,22},
  {42,3,44},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray28[10+1] = {
  {0,2,30},
  {3,2,30},
  {7,2,30},
  {14,2,30},
  {21,2,30},
  {22,2,30},
  {23,2,30},
  {24,2,30},
  {25,2,30},
  {28,2,30},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray29[7+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,45},
  {35,3,34},
  {39,3,46},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray30[6+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,47},
  {35,3,34},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray31[19+1] = {
  {4,2,12},
  {5,2,12},
  {6,2,12},
  {8,2,12},
  {9,2,12},
  {11,2,12},
  {12,2,12},
  {13,2,12},
  {15,2,12},
  {16,2,12},
  {18,2,12},
  {19,2,12},
  {20,2,12},
  {22,2,12},
  {23,2,12},
  {24,2,12},
  {25,2,12},
  {27,2,12},
  {28,2,12},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray32[19+1] = {
  {4,2,13},
  {5,2,13},
  {6,2,13},
  {8,2,13},
  {9,2,13},
  {11,2,13},
  {12,2,13},
  {13,2,13},
  {15,2,13},
  {16,2,13},
  {18,2,13},
  {19,2,13},
  {20,2,13},
  {22,2,13},
  {23,2,13},
  {24,2,13},
  {25,2,13},
  {27,2,13},
  {28,2,13},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray33[8+1] = {
  {4,1,48},
  {5,1,49},
  {15,1,50},
  {16,1,51},
  {18,1,52},
  {19,1,53},
  {27,1,54},
  {30,3,55},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray34[19+1] = {
  {4,2,10},
  {5,2,10},
  {6,2,10},
  {8,2,10},
  {9,2,10},
  {11,2,10},
  {12,2,10},
  {13,2,10},
  {15,2,10},
  {16,2,10},
  {18,2,10},
  {19,2,10},
  {20,2,10},
  {22,2,10},
  {23,2,10},
  {24,2,10},
  {25,2,10},
  {27,2,10},
  {28,2,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray35[12+1] = {
  {13,1,13},
  {22,1,2},
  {23,1,14},
  {24,1,15},
  {25,1,16},
  {28,1,17},
  {31,3,18},
  {32,3,19},
  {33,3,20},
  {36,3,21},
  {38,3,22},
  {41,3,56},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray36[20+1] = {
  {6,1,57},
  {9,1,58},
  {11,1,59},
  {20,1,60},
  {29,3,61},
  {4,2,8},
  {5,2,8},
  {8,2,8},
  {12,2,8},
  {13,2,8},
  {15,2,8},
  {16,2,8},
  {18,2,8},
  {19,2,8},
  {22,2,8},
  {23,2,8},
  {24,2,8},
  {25,2,8},
  {27,2,8},
  {28,2,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray37[7+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,33},
  {35,3,34},
  {39,3,62},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray38[1+1] = {
  {7,1,63},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray39[9+1] = {
  {4,1,48},
  {5,1,49},
  {12,1,64},
  {15,1,50},
  {16,1,51},
  {18,1,52},
  {19,1,53},
  {27,1,54},
  {30,3,55},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray40[1+1] = {
  {12,1,65},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray41[10+1] = {
  {0,2,25},
  {3,2,25},
  {7,2,25},
  {14,2,25},
  {21,2,25},
  {22,2,25},
  {23,2,25},
  {24,2,25},
  {25,2,25},
  {28,2,25},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray42[9+1] = {
  {4,1,48},
  {5,1,49},
  {12,1,66},
  {15,1,50},
  {16,1,51},
  {18,1,52},
  {19,1,53},
  {27,1,54},
  {30,3,55},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray43[1+1] = {
  {12,1,67},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray44[10+1] = {
  {0,2,34},
  {3,2,34},
  {7,2,34},
  {14,2,34},
  {21,2,34},
  {22,2,34},
  {23,2,34},
  {24,2,34},
  {25,2,34},
  {28,2,34},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray45[9+1] = {
  {4,1,48},
  {5,1,49},
  {15,1,50},
  {16,1,51},
  {18,1,52},
  {19,1,53},
  {27,1,54},
  {30,3,55},
  {12,2,19},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray46[1+1] = {
  {12,2,20},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray47[5+1] = {
  {4,1,48},
  {8,1,68},
  {15,1,50},
  {27,1,54},
  {30,3,55},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray48[3+1] = {
  {7,2,1},
  {23,2,1},
  {26,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray49[6+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,69},
  {35,3,34},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray50[3+1] = {
  {7,2,0},
  {23,2,0},
  {26,2,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray51[6+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,70},
  {35,3,34},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray52[6+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,71},
  {35,3,34},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray53[6+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,72},
  {35,3,34},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray54[3+1] = {
  {7,2,2},
  {23,2,2},
  {26,2,2},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray55[5+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {35,3,34},
  {43,3,73},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray56[1+1] = {
  {21,1,74},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray57[3+1] = {
  {7,2,5},
  {23,2,5},
  {26,2,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray58[3+1] = {
  {7,2,3},
  {23,2,3},
  {26,2,3},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray59[3+1] = {
  {7,2,4},
  {23,2,4},
  {26,2,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray60[3+1] = {
  {7,2,6},
  {23,2,6},
  {26,2,6},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray61[4+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {35,3,75},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray62[1+1] = {
  {8,1,76},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray63[7+1] = {
  {7,1,30},
  {23,1,31},
  {26,1,32},
  {34,3,33},
  {35,3,34},
  {39,3,77},
  {43,3,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray64[10+1] = {
  {0,2,33},
  {3,2,33},
  {7,2,33},
  {14,2,33},
  {21,2,33},
  {22,2,33},
  {23,2,33},
  {24,2,33},
  {25,2,33},
  {28,2,33},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray65[10+1] = {
  {0,2,32},
  {3,2,32},
  {7,2,32},
  {14,2,32},
  {21,2,32},
  {22,2,32},
  {23,2,32},
  {24,2,32},
  {25,2,32},
  {28,2,32},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray66[1+1] = {
  {14,1,78},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray67[1+1] = {
  {14,1,79},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray68[19+1] = {
  {4,2,11},
  {5,2,11},
  {6,2,11},
  {8,2,11},
  {9,2,11},
  {11,2,11},
  {12,2,11},
  {13,2,11},
  {15,2,11},
  {16,2,11},
  {18,2,11},
  {19,2,11},
  {20,2,11},
  {22,2,11},
  {23,2,11},
  {24,2,11},
  {25,2,11},
  {27,2,11},
  {28,2,11},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray69[12+1] = {
  {4,1,48},
  {15,1,50},
  {27,1,54},
  {30,3,55},
  {8,2,14},
  {12,2,14},
  {13,2,14},
  {22,2,14},
  {23,2,14},
  {24,2,14},
  {25,2,14},
  {28,2,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray70[12+1] = {
  {4,1,48},
  {15,1,50},
  {27,1,54},
  {30,3,55},
  {8,2,16},
  {12,2,16},
  {13,2,16},
  {22,2,16},
  {23,2,16},
  {24,2,16},
  {25,2,16},
  {28,2,16},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray71[12+1] = {
  {4,1,48},
  {15,1,50},
  {27,1,54},
  {30,3,55},
  {8,2,15},
  {12,2,15},
  {13,2,15},
  {22,2,15},
  {23,2,15},
  {24,2,15},
  {25,2,15},
  {28,2,15},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray72[12+1] = {
  {4,1,48},
  {15,1,50},
  {27,1,54},
  {30,3,55},
  {8,2,17},
  {12,2,17},
  {13,2,17},
  {22,2,17},
  {23,2,17},
  {24,2,17},
  {25,2,17},
  {28,2,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray73[20+1] = {
  {6,1,57},
  {9,1,58},
  {11,1,59},
  {20,1,60},
  {29,3,61},
  {4,2,7},
  {5,2,7},
  {8,2,7},
  {12,2,7},
  {13,2,7},
  {15,2,7},
  {16,2,7},
  {18,2,7},
  {19,2,7},
  {22,2,7},
  {23,2,7},
  {24,2,7},
  {25,2,7},
  {27,2,7},
  {28,2,7},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray74[12+1] = {
  {13,1,13},
  {22,1,2},
  {23,1,14},
  {24,1,15},
  {25,1,16},
  {28,1,17},
  {31,3,18},
  {32,3,19},
  {33,3,20},
  {36,3,21},
  {38,3,22},
  {41,3,80},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray75[19+1] = {
  {4,2,9},
  {5,2,9},
  {6,2,9},
  {8,2,9},
  {9,2,9},
  {11,2,9},
  {12,2,9},
  {13,2,9},
  {15,2,9},
  {16,2,9},
  {18,2,9},
  {19,2,9},
  {20,2,9},
  {22,2,9},
  {23,2,9},
  {24,2,9},
  {25,2,9},
  {27,2,9},
  {28,2,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray76[12+1] = {
  {13,1,13},
  {22,1,2},
  {23,1,14},
  {24,1,15},
  {25,1,16},
  {28,1,17},
  {31,3,18},
  {32,3,19},
  {33,3,20},
  {36,3,21},
  {38,3,22},
  {41,3,81},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray77[1+1] = {
  {8,1,82},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray78[10+1] = {
  {0,2,37},
  {3,2,37},
  {7,2,37},
  {14,2,37},
  {21,2,37},
  {22,2,37},
  {23,2,37},
  {24,2,37},
  {25,2,37},
  {28,2,37},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray79[10+1] = {
  {0,2,36},
  {3,2,36},
  {7,2,36},
  {14,2,36},
  {21,2,36},
  {22,2,36},
  {23,2,36},
  {24,2,36},
  {25,2,36},
  {28,2,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray80[10+1] = {
  {0,2,18},
  {3,2,18},
  {7,2,18},
  {14,2,18},
  {21,2,18},
  {22,2,18},
  {23,2,18},
  {24,2,18},
  {25,2,18},
  {28,2,18},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray81[10+1] = {
  {0,2,21},
  {3,2,21},
  {7,2,21},
  {14,2,21},
  {21,2,21},
  {22,2,21},
  {23,2,21},
  {24,2,21},
  {25,2,21},
  {28,2,21},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray82[10+1] = {
  {0,2,22},
  {3,2,22},
  {7,2,22},
  {14,2,22},
  {21,2,22},
  {22,2,22},
  {23,2,22},
  {24,2,22},
  {25,2,22},
  {28,2,22},
  {-1,-1,-1}};



/*
struct SymbolStruct {
  short Kind;
  char *Name;
  };
*/
struct SymbolStruct GrammarSymbolArray[44] = {
  /*  0 */   {3,"EOF"},
  /*  1 */   {7,"Error"},
  /*  2 */   {2,"Whitespace"},
  /*  3 */   {1,"'"},
  /*  4 */   {1,"-"},
  /*  5 */   {1,"!="},
  /*  6 */   {1,"%"},
  /*  7 */   {1,"("},
  /*  8 */   {1,")"},
  /*  9 */   {1,"*"},
  /* 10 */   {1,","},
  /* 11 */   {1,"/"},
  /* 12 */   {1,";"},
  /* 13 */   {1,"{"},
  /* 14 */   {1,"}"},
  /* 15 */   {1,"+"},
  /* 16 */   {1,"<"},
  /* 17 */   {1,"="},
  /* 18 */   {1,"=="},
  /* 19 */   {1,">"},
  /* 20 */   {1,"AND"},
  /* 21 */   {1,"ELSE"},
  /* 22 */   {1,"FUNCTION"},
  /* 23 */   {1,"ID"},
  /* 24 */   {1,"IF"},
  /* 25 */   {1,"LOOP"},
  /* 26 */   {1,"NUM"},
  /* 27 */   {1,"OR"},
  /* 28 */   {1,"RETURN"},
  /* 29 */   {0,"ap"},
  /* 30 */   {0,"ar"},
  /* 31 */   {0,"attr"},
  /* 32 */   {0,"com"},
  /* 33 */   {0,"cond"},
  /* 34 */   {0,"e"},
  /* 35 */   {0,"f"},
  /* 36 */   {0,"function"},
  /* 37 */   {0,"lib"},
  /* 38 */   {0,"loop"},
  /* 39 */   {0,"opl"},
  /* 40 */   {0,"param"},
  /* 41 */   {0,"stm"},
  /* 42 */   {0,"stm_"},
  /* 43 */   {0,"t"} 
  };



/*
struct DfaEdgeStruct {
  int TargetState;
  char *CharacterSet;
  };
struct DfaStateStruct {
  int AcceptSymbol;
  int EdgeCount;
  struct DfaEdgeStruct *Edges;
  };
*/
struct DfaStateStruct GrammarDfaStateArray[53+1] = {
  /* 0 */    {-1,25,GrammarDfaEdgeArray0},
  /* 1 */    {2,1,GrammarDfaEdgeArray1},
  /* 2 */    {3,0,GrammarDfaEdgeArray2},
  /* 3 */    {4,0,GrammarDfaEdgeArray3},
  /* 4 */    {-1,1,GrammarDfaEdgeArray4},
  /* 5 */    {5,0,GrammarDfaEdgeArray5},
  /* 6 */    {6,0,GrammarDfaEdgeArray6},
  /* 7 */    {7,0,GrammarDfaEdgeArray7},
  /* 8 */    {8,0,GrammarDfaEdgeArray8},
  /* 9 */    {9,0,GrammarDfaEdgeArray9},
  /* 10 */    {10,0,GrammarDfaEdgeArray10},
  /* 11 */    {11,0,GrammarDfaEdgeArray11},
  /* 12 */    {12,0,GrammarDfaEdgeArray12},
  /* 13 */    {13,0,GrammarDfaEdgeArray13},
  /* 14 */    {14,0,GrammarDfaEdgeArray14},
  /* 15 */    {15,0,GrammarDfaEdgeArray15},
  /* 16 */    {16,0,GrammarDfaEdgeArray16},
  /* 17 */    {19,0,GrammarDfaEdgeArray17},
  /* 18 */    {-1,1,GrammarDfaEdgeArray18},
  /* 19 */    {-1,1,GrammarDfaEdgeArray19},
  /* 20 */    {20,0,GrammarDfaEdgeArray20},
  /* 21 */    {-1,1,GrammarDfaEdgeArray21},
  /* 22 */    {-1,1,GrammarDfaEdgeArray22},
  /* 23 */    {-1,1,GrammarDfaEdgeArray23},
  /* 24 */    {21,0,GrammarDfaEdgeArray24},
  /* 25 */    {-1,1,GrammarDfaEdgeArray25},
  /* 26 */    {-1,1,GrammarDfaEdgeArray26},
  /* 27 */    {-1,1,GrammarDfaEdgeArray27},
  /* 28 */    {-1,1,GrammarDfaEdgeArray28},
  /* 29 */    {-1,1,GrammarDfaEdgeArray29},
  /* 30 */    {-1,1,GrammarDfaEdgeArray30},
  /* 31 */    {-1,1,GrammarDfaEdgeArray31},
  /* 32 */    {22,0,GrammarDfaEdgeArray32},
  /* 33 */    {-1,1,GrammarDfaEdgeArray33},
  /* 34 */    {-1,1,GrammarDfaEdgeArray34},
  /* 35 */    {-1,1,GrammarDfaEdgeArray35},
  /* 36 */    {25,0,GrammarDfaEdgeArray36},
  /* 37 */    {-1,1,GrammarDfaEdgeArray37},
  /* 38 */    {-1,1,GrammarDfaEdgeArray38},
  /* 39 */    {26,0,GrammarDfaEdgeArray39},
  /* 40 */    {-1,1,GrammarDfaEdgeArray40},
  /* 41 */    {27,0,GrammarDfaEdgeArray41},
  /* 42 */    {-1,1,GrammarDfaEdgeArray42},
  /* 43 */    {-1,1,GrammarDfaEdgeArray43},
  /* 44 */    {-1,1,GrammarDfaEdgeArray44},
  /* 45 */    {-1,1,GrammarDfaEdgeArray45},
  /* 46 */    {-1,1,GrammarDfaEdgeArray46},
  /* 47 */    {28,0,GrammarDfaEdgeArray47},
  /* 48 */    {17,1,GrammarDfaEdgeArray48},
  /* 49 */    {18,0,GrammarDfaEdgeArray49},
  /* 50 */    {-1,2,GrammarDfaEdgeArray50},
  /* 51 */    {23,0,GrammarDfaEdgeArray51},
  /* 52 */    {24,0,GrammarDfaEdgeArray52},
  {-1,-1,NULL}};



/*
struct RuleStruct {
  int Head;
  int SymbolsCount;
  int *Symbols;
  char *Description;
  };
*/
struct RuleStruct GrammarRuleArray[42] = {
  /*  0 */   {30,1,GrammarRuleSymbolArray0,"<ar> ::= '+'"},
  /*  1 */   {30,1,GrammarRuleSymbolArray1,"<ar> ::= '-'"},
  /*  2 */   {30,1,GrammarRuleSymbolArray2,"<ar> ::= OR"},
  /*  3 */   {29,1,GrammarRuleSymbolArray3,"<ap> ::= '*'"},
  /*  4 */   {29,1,GrammarRuleSymbolArray4,"<ap> ::= '/'"},
  /*  5 */   {29,1,GrammarRuleSymbolArray5,"<ap> ::= '%'"},
  /*  6 */   {29,1,GrammarRuleSymbolArray6,"<ap> ::= AND"},
  /*  7 */   {34,3,GrammarRuleSymbolArray7,"<e> ::= <e> <ar> <t>"},
  /*  8 */   {34,1,GrammarRuleSymbolArray8,"<e> ::= <t>"},
  /*  9 */   {43,3,GrammarRuleSymbolArray9,"<t> ::= <t> <ap> <f>"},
  /* 10 */   {43,1,GrammarRuleSymbolArray10,"<t> ::= <f>"},
  /* 11 */   {35,3,GrammarRuleSymbolArray11,"<f> ::= '(' <e> ')'"},
  /* 12 */   {35,1,GrammarRuleSymbolArray12,"<f> ::= ID"},
  /* 13 */   {35,1,GrammarRuleSymbolArray13,"<f> ::= NUM"},
  /* 14 */   {39,3,GrammarRuleSymbolArray14,"<opl> ::= <e> '!=' <e>"},
  /* 15 */   {39,3,GrammarRuleSymbolArray15,"<opl> ::= <e> '==' <e>"},
  /* 16 */   {39,3,GrammarRuleSymbolArray16,"<opl> ::= <e> '<' <e>"},
  /* 17 */   {39,3,GrammarRuleSymbolArray17,"<opl> ::= <e> '>' <e>"},
  /* 18 */   {33,5,GrammarRuleSymbolArray18,"<cond> ::= IF <opl> <stm> ELSE <stm>"},
  /* 19 */   {31,3,GrammarRuleSymbolArray19,"<attr> ::= ID '=' <e>"},
  /* 20 */   {31,3,GrammarRuleSymbolArray20,"<attr> ::= ID '=' <opl>"},
  /* 21 */   {38,5,GrammarRuleSymbolArray21,"<loop> ::= LOOP '(' <opl> ')' <stm>"},
  /* 22 */   {38,5,GrammarRuleSymbolArray22,"<loop> ::= LOOP <stm> '(' <opl> ')'"},
  /* 23 */   {32,1,GrammarRuleSymbolArray23,"<com> ::= <loop>"},
  /* 24 */   {32,1,GrammarRuleSymbolArray24,"<com> ::= <cond>"},
  /* 25 */   {32,2,GrammarRuleSymbolArray25,"<com> ::= <attr> ';'"},
  /* 26 */   {32,1,GrammarRuleSymbolArray26,"<com> ::= <function>"},
  /* 27 */   {37,2,GrammarRuleSymbolArray27,"<lib> ::= <function> <lib>"},
  /* 28 */   {37,1,GrammarRuleSymbolArray28,"<lib> ::= <function>"},
  /* 29 */   {37,1,GrammarRuleSymbolArray29,"<lib> ::= ''"},
  /* 30 */   {41,2,GrammarRuleSymbolArray30,"<stm> ::= '{' <stm_>"},
  /* 31 */   {41,1,GrammarRuleSymbolArray31,"<stm> ::= <com>"},
  /* 32 */   {41,3,GrammarRuleSymbolArray32,"<stm> ::= RETURN <opl> ';'"},
  /* 33 */   {41,3,GrammarRuleSymbolArray33,"<stm> ::= RETURN <e> ';'"},
  /* 34 */   {42,2,GrammarRuleSymbolArray34,"<stm_> ::= <com> <stm_>"},
  /* 35 */   {42,1,GrammarRuleSymbolArray35,"<stm_> ::= '}'"},
  /* 36 */   {42,4,GrammarRuleSymbolArray36,"<stm_> ::= RETURN <opl> ';' '}'"},
  /* 37 */   {42,4,GrammarRuleSymbolArray37,"<stm_> ::= RETURN <e> ';' '}'"},
  /* 38 */   {36,5,GrammarRuleSymbolArray38,"<function> ::= FUNCTION ID '(' <param> <stm>"},
  /* 39 */   {40,2,GrammarRuleSymbolArray39,"<param> ::= ID ')'"},
  /* 40 */   {40,1,GrammarRuleSymbolArray40,"<param> ::= ')'"},
  /* 41 */   {40,3,GrammarRuleSymbolArray41,"<param> ::= ID ',' <param>"} 
  };



/*
struct ActionStruct {
  int Entry;
  short Action;
  int Target;
  };
struct LalrStateStruct {
  int ActionCount;
  struct ActionStruct *Actions;
  };
*/
struct LalrStateStruct GrammarLalrStateArray[83+1] = {
  /* 0 */   {4,GrammarLalrActionArray0},
  /* 1 */   {1,GrammarLalrActionArray1},
  /* 2 */   {1,GrammarLalrActionArray2},
  /* 3 */   {5,GrammarLalrActionArray3},
  /* 4 */   {1,GrammarLalrActionArray4},
  /* 5 */   {1,GrammarLalrActionArray5},
  /* 6 */   {1,GrammarLalrActionArray6},
  /* 7 */   {3,GrammarLalrActionArray7},
  /* 8 */   {6,GrammarLalrActionArray8},
  /* 9 */   {2,GrammarLalrActionArray9},
  /* 10 */   {12,GrammarLalrActionArray10},
  /* 11 */   {6,GrammarLalrActionArray11},
  /* 12 */   {3,GrammarLalrActionArray12},
  /* 13 */   {12,GrammarLalrActionArray13},
  /* 14 */   {1,GrammarLalrActionArray14},
  /* 15 */   {7,GrammarLalrActionArray15},
  /* 16 */   {13,GrammarLalrActionArray16},
  /* 17 */   {7,GrammarLalrActionArray17},
  /* 18 */   {1,GrammarLalrActionArray18},
  /* 19 */   {10,GrammarLalrActionArray19},
  /* 20 */   {10,GrammarLalrActionArray20},
  /* 21 */   {10,GrammarLalrActionArray21},
  /* 22 */   {10,GrammarLalrActionArray22},
  /* 23 */   {10,GrammarLalrActionArray23},
  /* 24 */   {6,GrammarLalrActionArray24},
  /* 25 */   {10,GrammarLalrActionArray25},
  /* 26 */   {7,GrammarLalrActionArray26},
  /* 27 */   {12,GrammarLalrActionArray27},
  /* 28 */   {10,GrammarLalrActionArray28},
  /* 29 */   {7,GrammarLalrActionArray29},
  /* 30 */   {6,GrammarLalrActionArray30},
  /* 31 */   {19,GrammarLalrActionArray31},
  /* 32 */   {19,GrammarLalrActionArray32},
  /* 33 */   {8,GrammarLalrActionArray33},
  /* 34 */   {19,GrammarLalrActionArray34},
  /* 35 */   {12,GrammarLalrActionArray35},
  /* 36 */   {20,GrammarLalrActionArray36},
  /* 37 */   {7,GrammarLalrActionArray37},
  /* 38 */   {1,GrammarLalrActionArray38},
  /* 39 */   {9,GrammarLalrActionArray39},
  /* 40 */   {1,GrammarLalrActionArray40},
  /* 41 */   {10,GrammarLalrActionArray41},
  /* 42 */   {9,GrammarLalrActionArray42},
  /* 43 */   {1,GrammarLalrActionArray43},
  /* 44 */   {10,GrammarLalrActionArray44},
  /* 45 */   {9,GrammarLalrActionArray45},
  /* 46 */   {1,GrammarLalrActionArray46},
  /* 47 */   {5,GrammarLalrActionArray47},
  /* 48 */   {3,GrammarLalrActionArray48},
  /* 49 */   {6,GrammarLalrActionArray49},
  /* 50 */   {3,GrammarLalrActionArray50},
  /* 51 */   {6,GrammarLalrActionArray51},
  /* 52 */   {6,GrammarLalrActionArray52},
  /* 53 */   {6,GrammarLalrActionArray53},
  /* 54 */   {3,GrammarLalrActionArray54},
  /* 55 */   {5,GrammarLalrActionArray55},
  /* 56 */   {1,GrammarLalrActionArray56},
  /* 57 */   {3,GrammarLalrActionArray57},
  /* 58 */   {3,GrammarLalrActionArray58},
  /* 59 */   {3,GrammarLalrActionArray59},
  /* 60 */   {3,GrammarLalrActionArray60},
  /* 61 */   {4,GrammarLalrActionArray61},
  /* 62 */   {1,GrammarLalrActionArray62},
  /* 63 */   {7,GrammarLalrActionArray63},
  /* 64 */   {10,GrammarLalrActionArray64},
  /* 65 */   {10,GrammarLalrActionArray65},
  /* 66 */   {1,GrammarLalrActionArray66},
  /* 67 */   {1,GrammarLalrActionArray67},
  /* 68 */   {19,GrammarLalrActionArray68},
  /* 69 */   {12,GrammarLalrActionArray69},
  /* 70 */   {12,GrammarLalrActionArray70},
  /* 71 */   {12,GrammarLalrActionArray71},
  /* 72 */   {12,GrammarLalrActionArray72},
  /* 73 */   {20,GrammarLalrActionArray73},
  /* 74 */   {12,GrammarLalrActionArray74},
  /* 75 */   {19,GrammarLalrActionArray75},
  /* 76 */   {12,GrammarLalrActionArray76},
  /* 77 */   {1,GrammarLalrActionArray77},
  /* 78 */   {10,GrammarLalrActionArray78},
  /* 79 */   {10,GrammarLalrActionArray79},
  /* 80 */   {10,GrammarLalrActionArray80},
  /* 81 */   {10,GrammarLalrActionArray81},
  /* 82 */   {10,GrammarLalrActionArray82},
  {-1,NULL}};



/*
struct GrammarStruct {
  char CaseSensitive;
  int InitialSymbol;
  int InitialDfaState;
  int InitialLalrState;
  int SymbolCount;
  struct SymbolStruct *SymbolArray;
  int RuleCount;
  struct RuleStruct *RuleArray;
  int DfaStateCount;
  struct DfaStateStruct *DfaArray;
  int LalrStateCount;
  struct LalrStateStruct *LalrArray;
  };
*/
struct GrammarStruct Grammar = {
  /* CaseSensitive */      ,
  /* InitialSymbol */      ,
  /* InitialDfaState */    0,
  /* InitialLalrState */   0,
  /* SymbolCount */        44,
  /* SymbolArray */        GrammarSymbolArray,
  /* RuleCount */          42,
  /* RuleArray */          GrammarRuleArray,
  /* DfaStateCount */      53,
  /* DfaArray */           GrammarDfaStateArray,
  /* LalrStateCount */     83,
  /* LalrArray */          GrammarLalrStateArray
  };
