/* Generated by re2c 2.0.3 on Thu May 20 20:51:59 2021 */
#line 1 "lex_an.re"
#include "lex_an.h"

void write_ts(const char * ident, char * label, int line, TS * ts,int value){
	entries_t entrie;
	strcpy(entrie.ident, ident);
	strcpy(entrie.label, label);
	entrie.id=ts->qnt_entries;
	entrie.line = line;
	entrie.value = value;
	ts->entries[ts->qnt_entries++] = entrie;
}

static int lex(const char *YYCURSOR, const int line, TS * ts)
{
//	fprintf(stderr,"%s\n",YYCURSOR);
//	const char *YYMARKER;
	const char * saved = YYCURSOR;
    loop:
		saved = YYCURSOR;
    
#line 24 "lex_an.c"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '!':	goto yy6;
	case '"':	goto yy7;
	case '(':	goto yy9;
	case ')':	goto yy11;
	case '*':	goto yy13;
	case '+':	goto yy15;
	case '-':	goto yy17;
	case '.':	goto yy19;
	case '/':	goto yy21;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy23;
	case ';':	goto yy26;
	case '=':	goto yy28;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	case 'e':	goto yy33;
	case 'f':	goto yy34;
	case 'i':	goto yy35;
	case 'l':	goto yy36;
	case 'r':	goto yy37;
	case '{':	goto yy38;
	case '}':	goto yy40;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 52 "lex_an.re"
	{ return 0; }
#line 111 "lex_an.c"
yy4:
	++YYCURSOR;
yy5:
#line 78 "lex_an.re"
	{write_ts(saved,"ERR", line, ts,0); return 0;}
#line 117 "lex_an.c"
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy42;
	default:	goto yy5;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
	case '"':	goto yy44;
	default:	goto yy7;
	}
yy9:
	++YYCURSOR;
#line 65 "lex_an.re"
	{write_ts(saved,"(", line, ts,0); goto loop;}
#line 134 "lex_an.c"
yy11:
	++YYCURSOR;
#line 66 "lex_an.re"
	{write_ts(saved,")", line, ts,0); goto loop;}
#line 139 "lex_an.c"
yy13:
	++YYCURSOR;
#line 69 "lex_an.re"
	{write_ts(saved,"*", line, ts,0); goto loop;}
#line 144 "lex_an.c"
yy15:
	++YYCURSOR;
#line 67 "lex_an.re"
	{write_ts(saved,"+", line, ts,0); goto loop;}
#line 149 "lex_an.c"
yy17:
	++YYCURSOR;
#line 68 "lex_an.re"
	{write_ts(saved,"-", line, ts,0); goto loop;}
#line 154 "lex_an.c"
yy19:
	++YYCURSOR;
#line 75 "lex_an.re"
	{write_ts(saved,".", line, ts,0); goto loop;}
#line 159 "lex_an.c"
yy21:
	++YYCURSOR;
#line 70 "lex_an.re"
	{write_ts(saved,"/", line, ts,0); goto loop;}
#line 164 "lex_an.c"
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy46;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy23;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy25;
	}
yy25:
#line 60 "lex_an.re"
	{
			write_ts(saved,"NUM", line, ts,atoi(saved));
			goto loop;}
#line 239 "lex_an.c"
yy26:
	++YYCURSOR;
#line 74 "lex_an.re"
	{write_ts(saved,";", line, ts,0); goto loop;}
#line 244 "lex_an.c"
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy50;
	default:	goto yy29;
	}
yy29:
#line 73 "lex_an.re"
	{write_ts(saved,"=", line, ts,0); goto loop;}
#line 254 "lex_an.c"
yy30:
	yych = *++YYCURSOR;
yy31:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	default:	goto yy32;
	}
yy32:
#line 59 "lex_an.re"
	{write_ts(saved,"ID", line, ts,0); goto loop;}
#line 327 "lex_an.c"
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy52;
	default:	goto yy31;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy53;
	default:	goto yy31;
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy54;
	default:	goto yy31;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy56;
	default:	goto yy31;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy57;
	default:	goto yy31;
	}
yy38:
	++YYCURSOR;
#line 63 "lex_an.re"
	{write_ts(saved,"{", line, ts,0); goto loop;}
#line 362 "lex_an.c"
yy40:
	++YYCURSOR;
#line 64 "lex_an.re"
	{write_ts(saved,"}", line, ts,0); goto loop;}
#line 367 "lex_an.c"
yy42:
	++YYCURSOR;
#line 72 "lex_an.re"
	{write_ts(saved,"!=", line, ts,0); goto loop;}
#line 372 "lex_an.c"
yy44:
	++YYCURSOR;
#line 76 "lex_an.re"
	{write_ts(saved,"STR", line, ts,0); goto loop;}
#line 377 "lex_an.c"
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy46;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy48;
	default:	goto yy25;
	}
yy48:
	++YYCURSOR;
#line 77 "lex_an.re"
	{write_ts(saved,"ERR", line, ts,0); return 0;}
#line 450 "lex_an.c"
yy50:
	++YYCURSOR;
#line 71 "lex_an.re"
	{write_ts(saved,"==", line, ts,0); goto loop;}
#line 455 "lex_an.c"
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy58;
	default:	goto yy31;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy59;
	default:	goto yy31;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	default:	goto yy55;
	}
yy55:
#line 57 "lex_an.re"
	{write_ts(saved,"IF", line, ts,0); goto loop;}
#line 539 "lex_an.c"
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy60;
	default:	goto yy31;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy61;
	default:	goto yy31;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy62;
	default:	goto yy31;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy64;
	default:	goto yy31;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy65;
	default:	goto yy31;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy67;
	default:	goto yy31;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	default:	goto yy63;
	}
yy63:
#line 58 "lex_an.re"
	{write_ts(saved,"ELSE", line, ts,0); goto loop;}
#line 647 "lex_an.c"
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy68;
	default:	goto yy31;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	default:	goto yy66;
	}
yy66:
#line 56 "lex_an.re"
	{write_ts(saved,"LOOP", line, ts,0); goto loop;}
#line 725 "lex_an.c"
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy69;
	default:	goto yy31;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy70;
	default:	goto yy31;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy71;
	default:	goto yy31;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy73;
	default:	goto yy31;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	default:	goto yy72;
	}
yy72:
#line 54 "lex_an.re"
	{write_ts(saved,"RETURN", line, ts,0); goto loop;}
#line 821 "lex_an.c"
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy74;
	default:	goto yy31;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy30;
	default:	goto yy75;
	}
yy75:
#line 55 "lex_an.re"
	{write_ts(saved,"FUNCTION", line, ts,0); goto loop;}
#line 899 "lex_an.c"
}
#line 79 "lex_an.re"


}


void lex_check(char * file, TS * ts){
	FILE * fp = fopen(file,"r");
	FILE * of = fopen("lex.output","w");
//	fseek(fp,0,-1);
//	int size = ftell(fp);
//	fseek(fp,0,0);
	char c;
	int line = 1;
	char word[1000]; int wc = 0;
//	char buffer[1000];
	while (!feof(fp)){
		c = fgetc(fp);
//		putchar(c);
		if(c==' '||c=='\n'||c=='\t'){
			if (c == '\n')
				line ++;
			if (strlen(word) >= 1)
				lex(word,line, ts);
			for (int i = 0; i < wc; i++) word[i]=0;
			wc = 0;
		}else
			word[wc++] = c;
	}
	fclose(fp);
	printf("TS entries: %d\n TABLE:\n",ts->qnt_entries);
	printf("\n\tid\tiden\tlabel\t\tline\t\tvalue\n");
	for (int i=0; i<ts->qnt_entries; i++){
		entries_t entrie = ts->entries[i];
		char * str = entrie.label;
		printf("%d\t%s\t\t%s\t\t%d\t\t%d\n",entrie.id,entrie.ident,str,entrie.line,entrie.value);
		if (strcmp(entrie.label,"ERR")==0)
			fprintf(stderr,"Erro na linha: %d\nIdentificador: %s\n",entrie.line,entrie.ident);
		fwrite(str,sizeof(char),strlen(str),of);
		fputc(' ',of);
	}
	fwrite("$\n",sizeof(char),2,of);
	fclose(of);
	printf("$\n");

	of = fopen("TS.out","w");
	fwrite(&(ts->qnt_entries),sizeof(int),1,of);
	fwrite(ts->entries,sizeof(entries_t),ts->qnt_entries,of);
	fclose(of);
/*    for (int i = 1; i < argc; ++i) {
        lex(argv[i]);
    }
	*/


}


int main(int argc, char **argv)
{
	char * file = argv[argc-1];
	TS ts;
	entries_t entries[1000];
	ts.qnt_entries = 0;
	ts.entries = entries;
	lex_check(file,&ts);
    return 0;
}
