/*

This file was generated by the "C - Kessels engine grammar.h" template.

*/

#ifndef GRAMMAR_H
#define GRAMMAR_H

#define GrammarCharset0CharCount 7
wchar_t GrammarCharset0[7+1] = {
  9,
  10,
  11,
  12,
  13,
  32,
  160,
  0};
#define GrammarCharset1CharCount 1
wchar_t GrammarCharset1[1+1] = {
  82,
  0};
#define GrammarCharset2CharCount 1
wchar_t GrammarCharset2[1+1] = {
  35,
  0};
#define GrammarCharset3CharCount 1
wchar_t GrammarCharset3[1+1] = {
  39,
  0};
#define GrammarCharset4CharCount 1
wchar_t GrammarCharset4[1+1] = {
  40,
  0};
#define GrammarCharset5CharCount 1
wchar_t GrammarCharset5[1+1] = {
  41,
  0};
#define GrammarCharset6CharCount 1
wchar_t GrammarCharset6[1+1] = {
  43,
  0};
#define GrammarCharset7CharCount 9
wchar_t GrammarCharset7[9+1] = {
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  0};
#define GrammarCharset8CharCount 1
wchar_t GrammarCharset8[1+1] = {
  48,
  0};
#define GrammarCharset9CharCount 1
wchar_t GrammarCharset9[1+1] = {
  112,
  0};
#define GrammarCharset10CharCount 1
wchar_t GrammarCharset10[1+1] = {
  42,
  0};
#define GrammarCharset11CharCount 1
wchar_t GrammarCharset11[1+1] = {
  45,
  0};
#define GrammarCharset12CharCount 1
wchar_t GrammarCharset12[1+1] = {
  47,
  0};
#define GrammarCharset13CharCount 1
wchar_t GrammarCharset13[1+1] = {
  69,
  0};
#define GrammarCharset14CharCount 1
wchar_t GrammarCharset14[1+1] = {
  77,
  0};
#define GrammarCharset15CharCount 10
wchar_t GrammarCharset15[10+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  0};
#define GrammarCharset16CharCount 1
wchar_t GrammarCharset16[1+1] = {
  114,
  0};
#define GrammarCharset17CharCount 1
wchar_t GrammarCharset17[1+1] = {
  105,
  0};
#define GrammarCharset18CharCount 1
wchar_t GrammarCharset18[1+1] = {
  110,
  0};
#define GrammarCharset19CharCount 1
wchar_t GrammarCharset19[1+1] = {
  116,
  0};


/*
struct DfaEdgeStruct {
  int TargetState;
  int CharCount;
  wchar_t *CharacterSet;
  };
*/
struct DfaEdgeStruct GrammarDfaEdgeArray0[13+1] = {
  {1,GrammarCharset0CharCount,GrammarCharset0},
  {2,GrammarCharset1CharCount,GrammarCharset1},
  {5,GrammarCharset2CharCount,GrammarCharset2},
  {6,GrammarCharset3CharCount,GrammarCharset3},
  {7,GrammarCharset4CharCount,GrammarCharset4},
  {8,GrammarCharset5CharCount,GrammarCharset5},
  {9,GrammarCharset6CharCount,GrammarCharset6},
  {10,GrammarCharset7CharCount,GrammarCharset7},
  {12,GrammarCharset8CharCount,GrammarCharset8},
  {13,GrammarCharset9CharCount,GrammarCharset9},
  {18,GrammarCharset10CharCount,GrammarCharset10},
  {20,GrammarCharset11CharCount,GrammarCharset11},
  {22,GrammarCharset12CharCount,GrammarCharset12},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray1[1+1] = {
  {1,GrammarCharset0CharCount,GrammarCharset0},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray2[1+1] = {
  {3,GrammarCharset13CharCount,GrammarCharset13},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray3[1+1] = {
  {4,GrammarCharset14CharCount,GrammarCharset14},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray4[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray5[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray6[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray7[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray8[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray9[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray10[1+1] = {
  {11,GrammarCharset15CharCount,GrammarCharset15},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray11[1+1] = {
  {11,GrammarCharset15CharCount,GrammarCharset15},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray12[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray13[1+1] = {
  {14,GrammarCharset16CharCount,GrammarCharset16},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray14[1+1] = {
  {15,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray15[1+1] = {
  {16,GrammarCharset18CharCount,GrammarCharset18},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray16[1+1] = {
  {17,GrammarCharset19CharCount,GrammarCharset19},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray17[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray18[1+1] = {
  {19,GrammarCharset12CharCount,GrammarCharset12},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray19[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray20[1+1] = {
  {21,GrammarCharset11CharCount,GrammarCharset11},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray21[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray22[2+1] = {
  {23,GrammarCharset12CharCount,GrammarCharset12},
  {24,GrammarCharset10CharCount,GrammarCharset10},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray23[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray24[0+1] = {
  {-1,0,NULL}};



int GrammarRuleSymbolArray0[2+1] = {
  14,
  15,
  -1};
int GrammarRuleSymbolArray1[0+1] = {
  -1};
int GrammarRuleSymbolArray2[4+1] = {
  13,
  7,
  16,
  8,
  -1};
int GrammarRuleSymbolArray3[3+1] = {
  17,
  11,
  16,
  -1};
int GrammarRuleSymbolArray4[3+1] = {
  17,
  6,
  16,
  -1};
int GrammarRuleSymbolArray5[1+1] = {
  17,
  -1};
int GrammarRuleSymbolArray6[3+1] = {
  18,
  9,
  17,
  -1};
int GrammarRuleSymbolArray7[3+1] = {
  18,
  10,
  17,
  -1};
int GrammarRuleSymbolArray8[1+1] = {
  18,
  -1};
int GrammarRuleSymbolArray9[1+1] = {
  12,
  -1};
int GrammarRuleSymbolArray10[3+1] = {
  7,
  16,
  8,
  -1};


struct ActionStruct GrammarLalrActionArray0[4+1] = {
  {13,1,1},
  {14,3,2},
  {15,3,3},
  {0,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray1[1+1] = {
  {7,1,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray2[4+1] = {
  {13,1,1},
  {14,3,2},
  {15,3,5},
  {0,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray3[1+1] = {
  {0,4,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray4[5+1] = {
  {7,1,6},
  {12,1,7},
  {16,3,8},
  {17,3,9},
  {18,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray5[1+1] = {
  {0,2,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray6[5+1] = {
  {7,1,6},
  {12,1,7},
  {16,3,11},
  {17,3,9},
  {18,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray7[5+1] = {
  {6,2,9},
  {8,2,9},
  {9,2,9},
  {10,2,9},
  {11,2,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray8[1+1] = {
  {8,1,12},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray9[3+1] = {
  {6,1,13},
  {11,1,14},
  {8,2,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray10[5+1] = {
  {9,1,15},
  {10,1,16},
  {6,2,8},
  {8,2,8},
  {11,2,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray11[1+1] = {
  {8,1,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray12[2+1] = {
  {0,2,2},
  {13,2,2},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray13[5+1] = {
  {7,1,6},
  {12,1,7},
  {16,3,18},
  {17,3,9},
  {18,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray14[5+1] = {
  {7,1,6},
  {12,1,7},
  {16,3,19},
  {17,3,9},
  {18,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray15[4+1] = {
  {7,1,6},
  {12,1,7},
  {17,3,20},
  {18,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray16[4+1] = {
  {7,1,6},
  {12,1,7},
  {17,3,21},
  {18,3,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray17[5+1] = {
  {6,2,10},
  {8,2,10},
  {9,2,10},
  {10,2,10},
  {11,2,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray18[1+1] = {
  {8,2,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray19[1+1] = {
  {8,2,3},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray20[3+1] = {
  {6,2,6},
  {8,2,6},
  {11,2,6},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray21[3+1] = {
  {6,2,7},
  {8,2,7},
  {11,2,7},
  {-1,-1,-1}};



/*
struct SymbolStruct {
  short Kind;
  wchar_t *Name;
  };
*/
struct SymbolStruct GrammarSymbolArray[19] = {
  /* 0   */   {3,L"EOF"},
  /* 1   */   {7,L"Error"},
  /* 2   */   {2,L"Whitespace"},
  /* 3   */   {5,L"Comment End"},
  /* 4   */   {6,L"Comment Line"},
  /* 5   */   {4,L"Comment Start"},
  /* 6   */   {1,L"-"},
  /* 7   */   {1,L"("},
  /* 8   */   {1,L")"},
  /* 9   */   {1,L"*"},
  /* 10  */   {1,L"/"},
  /* 11  */   {1,L"+"},
  /* 12  */   {1,L"DecLiteral"},
  /* 13  */   {1,L"print"},
  /* 14  */   {0,L"Calculate"},
  /* 15  */   {0,L"Calculations"},
  /* 16  */   {0,L"Expression"},
  /* 17  */   {0,L"MultiplyDivide"},
  /* 18  */   {0,L"Value"} 
  };



/*
struct DfaEdgeStruct {
  int TargetState;
  wchar_t *CharacterSet;
  };
struct DfaStateStruct {
  int AcceptSymbol;
  int EdgeCount;
  struct DfaEdgeStruct *Edges;
  };
*/
struct DfaStateStruct GrammarDfaStateArray[25+1] = {
  /* 0 */    {-1,13,GrammarDfaEdgeArray0},
  /* 1 */    {2,1,GrammarDfaEdgeArray1},
  /* 2 */    {-1,1,GrammarDfaEdgeArray2},
  /* 3 */    {-1,1,GrammarDfaEdgeArray3},
  /* 4 */    {4,0,GrammarDfaEdgeArray4},
  /* 5 */    {4,0,GrammarDfaEdgeArray5},
  /* 6 */    {4,0,GrammarDfaEdgeArray6},
  /* 7 */    {7,0,GrammarDfaEdgeArray7},
  /* 8 */    {8,0,GrammarDfaEdgeArray8},
  /* 9 */    {11,0,GrammarDfaEdgeArray9},
  /* 10 */    {12,1,GrammarDfaEdgeArray10},
  /* 11 */    {12,1,GrammarDfaEdgeArray11},
  /* 12 */    {12,0,GrammarDfaEdgeArray12},
  /* 13 */    {-1,1,GrammarDfaEdgeArray13},
  /* 14 */    {-1,1,GrammarDfaEdgeArray14},
  /* 15 */    {-1,1,GrammarDfaEdgeArray15},
  /* 16 */    {-1,1,GrammarDfaEdgeArray16},
  /* 17 */    {13,0,GrammarDfaEdgeArray17},
  /* 18 */    {9,1,GrammarDfaEdgeArray18},
  /* 19 */    {3,0,GrammarDfaEdgeArray19},
  /* 20 */    {6,1,GrammarDfaEdgeArray20},
  /* 21 */    {4,0,GrammarDfaEdgeArray21},
  /* 22 */    {10,2,GrammarDfaEdgeArray22},
  /* 23 */    {4,0,GrammarDfaEdgeArray23},
  /* 24 */    {5,0,GrammarDfaEdgeArray24},
  {-1,-1,NULL}};



/*
struct RuleStruct {
  int Head;
  int SymbolsCount;
  int *Symbols;
  wchar_t *Description;
  };
*/
struct RuleStruct GrammarRuleArray[11] = {
  /* 0   */   {15,2,GrammarRuleSymbolArray0,L"<Calculations> ::= <Calculate> <Calculations>"},
  /* 1   */   {15,0,GrammarRuleSymbolArray1,L"<Calculations> ::= "},
  /* 2   */   {14,4,GrammarRuleSymbolArray2,L"<Calculate> ::= print '(' <Expression> ')'"},
  /* 3   */   {16,3,GrammarRuleSymbolArray3,L"<Expression> ::= <MultiplyDivide> '+' <Expression>"},
  /* 4   */   {16,3,GrammarRuleSymbolArray4,L"<Expression> ::= <MultiplyDivide> '-' <Expression>"},
  /* 5   */   {16,1,GrammarRuleSymbolArray5,L"<Expression> ::= <MultiplyDivide>"},
  /* 6   */   {17,3,GrammarRuleSymbolArray6,L"<MultiplyDivide> ::= <Value> '*' <MultiplyDivide>"},
  /* 7   */   {17,3,GrammarRuleSymbolArray7,L"<MultiplyDivide> ::= <Value> '/' <MultiplyDivide>"},
  /* 8   */   {17,1,GrammarRuleSymbolArray8,L"<MultiplyDivide> ::= <Value>"},
  /* 9   */   {18,1,GrammarRuleSymbolArray9,L"<Value> ::= DecLiteral"},
  /* 10  */   {18,3,GrammarRuleSymbolArray10,L"<Value> ::= '(' <Expression> ')'"} 
  };



/*
struct ActionStruct {
  int Entry;
  short Action;
  int Target;
  };
struct LalrStateStruct {
  int ActionCount;
  struct ActionStruct *Actions;
  };
*/
struct LalrStateStruct GrammarLalrStateArray[22+1] = {
  /* 0 */   {4,GrammarLalrActionArray0},
  /* 1 */   {1,GrammarLalrActionArray1},
  /* 2 */   {4,GrammarLalrActionArray2},
  /* 3 */   {1,GrammarLalrActionArray3},
  /* 4 */   {5,GrammarLalrActionArray4},
  /* 5 */   {1,GrammarLalrActionArray5},
  /* 6 */   {5,GrammarLalrActionArray6},
  /* 7 */   {5,GrammarLalrActionArray7},
  /* 8 */   {1,GrammarLalrActionArray8},
  /* 9 */   {3,GrammarLalrActionArray9},
  /* 10 */   {5,GrammarLalrActionArray10},
  /* 11 */   {1,GrammarLalrActionArray11},
  /* 12 */   {2,GrammarLalrActionArray12},
  /* 13 */   {5,GrammarLalrActionArray13},
  /* 14 */   {5,GrammarLalrActionArray14},
  /* 15 */   {4,GrammarLalrActionArray15},
  /* 16 */   {4,GrammarLalrActionArray16},
  /* 17 */   {5,GrammarLalrActionArray17},
  /* 18 */   {1,GrammarLalrActionArray18},
  /* 19 */   {1,GrammarLalrActionArray19},
  /* 20 */   {3,GrammarLalrActionArray20},
  /* 21 */   {3,GrammarLalrActionArray21},
  {-1,NULL}};



/*
struct GrammarStruct {
  char CaseSensitive;
  int InitialSymbol;
  int InitialDfaState;
  int InitialLalrState;
  int SymbolCount;
  struct SymbolStruct *SymbolArray;
  int RuleCount;
  struct RuleStruct *RuleArray;
  int DfaStateCount;
  struct DfaStateStruct *DfaArray;
  int LalrStateCount;
  struct LalrStateStruct *LalrArray;
  };
*/
struct GrammarStruct Grammar = {
  /* CaseSensitive */      True,
  /* InitialSymbol */      15,
  /* InitialDfaState */    0,
  /* InitialLalrState */   0,
  /* SymbolCount */        19,
  /* SymbolArray */        GrammarSymbolArray,
  /* RuleCount */          11,
  /* RuleArray */          GrammarRuleArray,
  /* DfaStateCount */      25,
  /* DfaArray */           GrammarDfaStateArray,
  /* LalrStateCount */     22,
  /* LalrArray */          GrammarLalrStateArray
  };
#endif
